version: '3.8'

services:
  metarep-app:
    build: .
    container_name: metarep-app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
      - PORT=5000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./migration_output:/app/migration_output
    restart: unless-stopped
    networks:
      - metarep-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ssl-manager:
    build:
      context: .
      dockerfile: Dockerfile.ssl
    container_name: metarep-ssl
    volumes:
      - ssl-certs:/etc/nginx/ssl
      - ./logs:/var/log
    restart: unless-stopped
    networks:
      - metarep-network
    healthcheck:
      test: ["CMD", "test", "-f", "/etc/nginx/ssl/cert.pem"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:alpine
    container_name: metarep-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ssl-certs:/etc/nginx/ssl:ro
    depends_on:
      ssl-manager:
        condition: service_healthy
      metarep-app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - metarep-network

volumes:
  ssl-certs:
    driver: local

networks:
  metarep-network:
    driver: bridge 